### ISSUE TITLE
remote ajax calls in the wizard

### ISSUE THREAD

**Issue by shenoudab** [kflorence/jquery-wizard#1]
Dear, 

 is it available to have a remote ajax calls and RESTful calls within the wizards and also in branching based on the ajax calls.
how to do so ..

Best Regards,
Shenouda Bertel

**Comment by casey1701** [comment]
Quick question to follow up on this async. I know this is old, but I'm using it anyways. I have a wizard going with a couple of transitions. Here is my code. Based on the result of servicelookup, I would like to go to a specific step. This doesn't work. What should I do?

`
<script type="text/javascript">
				$("#wrapped").wizard({
					transitions: {
						choosetv: function( $step, action ) {
							var tvchoice1 = $step.find("[name=tv_choice]:checked").val();
							if(tvchoice1 == 'Starter TV - $45/mo'){ return 'additionaltv'; }
							if(tvchoice1 == 'Advanced TV - $110/mo'){ return 'additionaltv'; }
							if(tvchoice1 == 'No TV - $0.00'){ return 'end'; }
						},
						servicelookup: function( $step, action ) {
							var service_address=$("#service_address").val();
							$.ajax({
								type:'post',
									url:'check_service_address.php',
									data:{service_address: service_address},
									success:function(data){
										if(data == 'not_in_list\r\n'){ 
										console.log("sorry");
										return('sorry');
										}
										if(data == 'in_list\r\n'){ 
										console.log("congratulations"); 
										return('internet');
										}
									}
							});
							
						}
						
					}
				});
</script> 
`
