### ISSUE TITLE
Branch reset input selected when going back

### ISSUE THREAD

**Issue by Mik75** [kflorence/jquery-wizard#18]
hello....i am using your script with branch method..i have a small issue

Question 1 -A go to question 2 (Client selects option A) -B go to question 2 Question 2 (Client wants to back to question 1 to select other option—> Selects A or B from question 2 due to required value) A B

(The problem is that the selected options from question 2 are now checked and saved, is it possible to auto-reset the options you have selected when going back? How?
thank you.

**Comment by kflorence** [comment]
@Mik75 I have added an example, see the commit above: https://github.com/kflorence/jquery-wizard/commit/970c8efca2b7ca8c43ce7020eacfc0138d27996e#diff-5b0e3367cfabe5a0173e80753b827d6cR87 -- let me know if this accurate with what you're trying to do.
