### ISSUE TITLE
Branch error messages

### ISSUE THREAD

**Issue by lightskinnnn38** [kflorence/jquery-wizard#38]
Hello!
I would like to display an error message next to each empty or non-valid field on each branch instead of the "alert" that is in the current example (Example 3). I was trying to add elements from Example 1 into Example 3 and I couldn't get it to work. My best guess is that I need to replace the line below with something else? 
```javascript
if ( !branch ) {
    alert( "Please select a value to continue." );
}
```

My wizard will contain both select and text fields.

Could you help me understand how to add error messages? Thank you!

**Comment by kflorence** [comment]
@lightskinnnn38 Yes, you will need to replace that logic with something else. Unfortunately, issues is not the best place for questions like this. Would you mind posting it on stackoverflow.com instead?
