### ISSUE TITLE
Responsiveness Support 

### ISSUE THREAD

**Issue by gayansolid** [kflorence/jquery-wizard#39]
this plugin isn't responsive .

**Comment by kflorence** [comment]
Can you be more specific?

**Comment by gayansolid** [comment]
when i go with bootstrap to support mobile as well this ui breaks responsiveness

**Comment by kflorence** [comment]
Are you talking about the examples? The plugin itself doesn't require any specific styling that I'm aware of.

**Comment by gayansolid** [comment]
ok i'm sorry about the misunderstanding. it supports bootstrap thanks for awesome plugin
