### ISSUE TITLE
Validation doesn't work in presence of labels

### ISSUE THREAD

**Issue by vsoch** [kflorence/jquery-wizard#40]
I am debugging an implementation of this that has questions with labels, which looks something like this:

      <p>I plan tasks carefully.</p>
      <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="option-bis11_survey_2_0">
      <input type="radio" id="option-bis11_survey_2_0" class="mdl-radio__button " name="bis11_survey_2_options" value="4" meta-options="Rarely/Never|Occasionally|Often|Almost Always/Always" meta-text="I plan tasks carefully.">
      <span class="mdl-radio__label">Rarely/Never</span>
      </label>
      <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="option-bis11_survey_2_1">

And I've debugged it as far as to verify that when I remove the labels, the validation finally starts working:

      <p>I plan tasks carefully.</p>
      <input type="radio" id="option-bis11_survey_2_0" class="mdl-radio__button " name="bis11_survey_2_options" value="4" meta-options="Rarely/Never|Occasionally|Often|Almost Always/Always" meta-text="I plan tasks carefully.">
      <span class="mdl-radio__label">Rarely/Never</span>

I'm guessing the bug has to do with not expecting the parent of an input to be a label, but I'm not sure where to fix it (I can't find anything). Any help would be greatly appreciated!

**Comment by kflorence** [comment]
I think this question would be better asked here: https://github.com/jzaefferer/jquery-validation

**Comment by vsoch** [comment]
Thanks anyway.
