### ISSUE TITLE
How to dynamic create steps

### ISSUE THREAD

**Issue by reficul** [kflorence/jquery-wizard#41]
I need help with my script.
I've a first step where I ask:

"How many reports do you want submit?"

Now I try to find a way to create X steps as answered in the first step.

Then, if I answered 3 reports I've something like:

Step 1 - Question how many...
Step 2 - Report 1
Step 3 - Report 2
Step 4 - Report 3

**Comment by kflorence** [comment]
I suppose you could `.destroy()` the wizard, add however many steps/branches you need, then re-initialize it. Since you're adding new steps it will need to recalculate it's internal state.

**Comment by kflorence** [comment]
@reficul see above for an example
