### ISSUE TITLE
Aync transitions and content

### ISSUE THREAD

**Issue by ant5** [kflorence/jquery-wizard#45]
Dear KFlorence,
I'm looking for a tools to help me implement an wizard-like form filling. Your solutions seems more apropriate to me than others.

I need to collect data from user step by step when each step depends on previously entered values. Also I can't put all variants in HTML because of they quantity. I think I have to AJAX all form values to backend and get back a next step fieldset then repeat this again till finish.

I found in you library:
- support of branches;
- "action" parameter of "transitions" function related to asynchronous;
- the claim of integrating jquery-wizard with jquery-form which allow to async form submit.

All of this make me sense that there is a possibility to achevie my goal with your wizard. 
But I don't fully understand how to do it. May be you can point me.

Sincerely yours,
Anthony

**Comment by casey1701** [comment]
Hello Ant5,

Did you ever figure this out? I am using it for a wizard order form. I've made an async call. I get a result and have conditions but I can't go to the needed next step. See my code below. Where it says return sorry, or return internet. It's not doing it. Do you know of a way for me to send the wizard to the right step?

```
				$("#wrapped").wizard({
					transitions: {
						choosetv: function( $step, action ) {
							var tvchoice1 = $step.find("[name=tv_choice]:checked").val();
							if(tvchoice1 == 'Starter TV - $45/mo'){ return 'additionaltv'; }
							if(tvchoice1 == 'Advanced TV - $110/mo'){ return 'additionaltv'; }
							if(tvchoice1 == 'No TV - $0.00'){ return 'end'; }
						},
						servicelookup: function( $step, action ) {
							var service_address=$("#service_address").val();
							$.ajax({
								type:'post',
									url:'check_service_address.php',
									data:{service_address: service_address},
									success:function(data){
										if(data == 'not_in_list\r\n'){ 
										console.log("sorry");
										return 'sorry';
										}
										if(data == 'in_list\r\n'){ 
										console.log("congratulations"); 
										return 'internet';
										}
									}
							});
							
						}
						
					}
				});
```

**Comment by kflorence** [comment]
Hello @casey1701 @ant5 -- sorry I missed this original question. The `action` method can be used to provide the correct result when using asynchronous transitions, see the example here: https://github.com/kflorence/jquery-wizard/blob/master/tests/unit/wizard/wizard_options.js#L179

By the way, in general you will probably get better/faster responses if you ask these questions in Stackoverflow, since I generally don't check here often except for bugs.
