### ISSUE TITLE
.on not supported in jQuery 1.6

### ISSUE THREAD

**Issue by ssendev** [kflorence/jquery-wizard#46]
.on was added in jQuery 1.7 http://api.jquery.com/on/ but the readme claims compatibility with 1.6

**Comment by kflorence** [comment]
@ssendev how are you trying to use `.on` and what issue are you having with it?

**Comment by ssendev** [comment]
i am not trying to use it it's used by jquery-wizard to attach to the forward/back buttons

**Comment by dush88gs** [comment]
@ssendev I think you should test the site by updating jQuery to version 1.7. If it doesn't help, try updating to the jQuery version 2.1.4. If the problem still consist I guess there is nothing to do with jQuery.

**Comment by ssendev** [comment]
On the page I build I worked around the problem. This issue exists because there is misleading information in the readme.

* jQuery `1.6` is listed as requirement https://github.com/kflorence/jquery-wizard/blob/1.1.3/readme.md#requirements
* but `.on` is used https://github.com/kflorence/jquery-wizard/blob/1.1.3/src/jquery.wizard.js#L152
* which is only available starting form jQuery `1.7` http://api.jquery.com/on/ 

So either the `.on` needs to be replaced with something `1.6` compliant or the readme needs to be updated to say `1.7` (though i don't know if there is something else that requires an even greater jQuery verison)

**Comment by kflorence** [comment]
Thanks for reporting @ssendev
