### ISSUE TITLE
hide or show step dynamically

### ISSUE THREAD

**Issue by dralbader** [kflorence/jquery-wizard#47]
Dear florence,

I need to remove or skip 1 step based on one value in the first step.
example : if user choose to make hotel reservation in the first step I want to show that step
if he don't choose that option I want to remove that step from the wizard.
is there a way to do that?

Thanks for your help.
Regards,

**Comment by jajourda** [comment]
$(".price_calc input[name='services-selected']").change(function () {
        // Remove previously added dynamic steps
        $('.price_calc').find(".step.dynamic").remove();
        // Add in selected number of steps
        for (var i = 0, l = 3; i < 3; i++) {
            console.log('for loop started');


            $('.submit').before(
                $("<div>").addClass("dynamic step row").text("Dynamically created step #" + (i + 1))
            );
        }
        // Destroy and re-create the wizard
        $('#wizard_container').wizard("destroy").wizard();


    });

**Comment by kflorence** [comment]
@dralbader you can "skip" steps just by providing a different step to transition to based on some logic. If you want those steps to be completely removed from the wizard dynamically (e.g. they would be removed from the progress calculations used by the wizard), then the example that @jajourda gave is the best way forward. If you dynamically add/remove any steps, you will need to destroy and re-create the wizard. note that you can re-initialize it with an `initialStep` value that could retain the history of how they got to the current step prior to destruction (by providing an array of values).
