### ISSUE TITLE
Issue Adding to Wordpress

### ISSUE THREAD

**Issue by twoodhouse02** [kflorence/jquery-wizard#49]
I have this up and running on a static page, but when I try to add it to a wordpress site using a custom page template, I get this error in the console: 

Uncaught TypeError: jQuery(...).wizard is not a function
    at HTMLDocument.<anonymous> ((index):592)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)

I am not super experienced in jQuery so any help is appreciated! 

Thank you so much for your help!

**Comment by dush88gs** [comment]
I have used this with the latest version of jQuery without having any issues. So first of all try to use latest version of jQuery.

`<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>`

If it doesn't help, try adding jquery-ui.min.js.
`<script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>`

I have fixed the same issue by adding jQuery UI.

**Comment by kflorence** [comment]
Please re-open with a reproducible case if this is still an issue.
