### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by casey1701** [kflorence/jquery-wizard#51]
Hey, I hate to make a new issue but I wanted to ask you a question. I have a wizard going with a couple of transitions. Here is my code. Based on the result of servicelookup, I would like to go to a specific step. This doesn't work. What should I do?

`<script type="text/javascript"> $("#wrapped").wizard({ transitions: { choosetv: function( $step, action ) { var tvchoice1 = $step.find("[name=tv_choice]:checked").val(); if(tvchoice1 == 'Starter TV - $45/mo'){ return 'additionaltv'; } if(tvchoice1 == 'Advanced TV - $110/mo'){ return 'additionaltv'; } if(tvchoice1 == 'No TV - $0.00'){ return 'end'; } }, servicelookup: function( $step, action ) { var service_address=$("#service_address").val(); $.ajax({ type:'post', url:'check_service_address.php', data:{service_address: service_address}, success:function(data){ if(data == 'not_in_list\r\n'){ console.log("sorry"); return('sorry'); } if(data == 'in_list\r\n'){ console.log("congratulations"); return('internet'); } } }); } } }); </script>`

**Comment by casey1701** [comment]
https://pastebin.com/WNebHLYs

**Comment by casey1701** [comment]
It throws the console.log's for sorry & congratulations correctly, but the returns don't work. I know its because that it is a different function, but I"m kind of at a loss how to get it back down to the right function. Is there a way to just directly go to a step and jump out of that success:

**Comment by kflorence** [comment]
Have you tried using the `action` method in your transition method? See https://github.com/kflorence/jquery-wizard/issues/45#issuecomment-565243622

**Comment by casey1701** [comment]
No I haven't. I will look into it though! Thanks. Do you have an example
anywhere of that?

**Comment by casey1701** [comment]
Hey that worked perfectly! Thanks so much!

Casey
